config/routes.rb
Rails.application.routes.draw do

  resources :tweets

  resources :hashtags

  get '/list_tweets' => 'list_tweets#index'

  post '/tweets_search' => 'tweets#search'

  root 'hashtags#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :tweets, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :hashtag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  # GET /hashtags
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1
  def show
    @hashtag = Hashtag.find(params[:id])
  end

  # GET hashtags/new
  def new
  end

  # POST /hashtags
  def create
    @hashtag = Hashtag.new(hashtag_params)

    if @hashtag.tag[0] != '#'
      @hashtag.tag = '#' + @hashtag.tag
    end
    
    if @hashtag.tag.match(/\S\s+/)
      @hashtag.tag = @hashtag.tag.strip
    end

    @hashtag.save

    # Using the SearchApiService
    search = SearchApiService.new(@hashtag)
    
    if search.search_api
      search.create_tweets(@hashtag)
      redirect_to @hashtag
    else
      puts "Deu ruim"
    end
  end

  # PATCH/PUT /hashtags/1
  def update
    @hashtag = Hashtag.find(params[:id])

    Tweet.where(hashtag_id: @hashtag.id).destroy_all

    # Using the SearchApiService
    search = SearchApiService.new(@hashtag)
    
    if search.search_api
      search.create_tweets(@hashtag)
      redirect_to @hashtag
    else
      puts "Deu ruim"
    end

  end

  # DELETE /hashtags/1
  def destroy
    @hashtag = Hashtag.find(params[:id])
    @hashtag.destroy

    redirect_to hashtags_url
  end

  private

    def hashtag_params
      params.require(:hashtag).permit(:tag)
    end

end

app/controllers/list_tweets_controller.rb
class ListTweetsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_class(flash_type)
      case flash_type.to_sym
      when :notice
        "alert-success"
      when :alert
        "alert-warning"
      when :error
        "alert-danger"
      end
    end
  end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/list_tweets_helper.rb
module ListTweetsHelper
end

app/views/hashtags/index.html.erb
<html>
  <head>
    <title>MineTweets</title>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <div class="columns">

          <h1> Mine Tweets Hashtags</h1>

          <br> <p> <%= link_to 'Show all tweets', list_tweets_path %> </p>
          <br> <p> <%= link_to 'Add Hashtag', new_hashtag_path %> </p>

          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Hashtag</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% @hashtags.each do |hash| %>

                  <tr>
                    <td> <%= hash.tag %> </td>
                    <td> <%= link_to 'Show', hashtag_path(hash) %> </td>
                    <td> <%= link_to 'Remove', hashtag_path(hash),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/hashtags/new.html.erb
<!-- app/views/hashtags/new.html.erb -->

<html>

  <head>
    <title>MineTweets</title>
  </head>

  <body>

    <section class="section">
      <div class="container">
        <div class="columns">

          <h1> Mine Tweets Hashtags</h1>

          <br> <p> <%= link_to 'Show all tweets', list_tweets_path %> </p>
          <br> <p> <%= link_to 'Back to Hashtags', hashtags_path %> </p>

          <div class='form-label-group'>
          
            <%= form_with scope: :hashtag, url: hashtags_path, local: true do |form| %>
              <p>
                <%= form.label :Search_Hashtag %><br>
                <%= form.text_field :tag %>
              </p>
              
              <p>
                <%= form.submit %>
              </p>
            <% end %>

          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/hashtags/show.html.erb
<head>
  <title>MineTweets</title>
</head>

<body>

  <div class="tweetEntry-tweetHolder">

    <p> <%= link_to 'Back to Home', hashtags_path %> </p>

    <div class="link-update"> <%= link_to 'Update', hashtag_path(@hashtag.id), method: :put %> </div>

    <% Tweet.where(hashtag_id: @hashtag.id).each do | tw | %>

      <div class="tweetEntry">

        <div class="tweetEntry-content">

          <img class="tweetEntry-avatar" src= <%= tw.url_img_user %> >

          <strong class="tweetEntry-fullname"> <%= tw.user_name %> </strong>

          <span class="tweetEntry-username"> <b> @<%= tw.user_screen_name %> </b> </span>

          <span class="tweetEntry-timestamp"> <%= tw.date_post %> </span>

          <div class="tweetEntry-text-container"> <%= tw.tweet_desc %> </div>

        </div>
      </div>

    <% end %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <title>MineTweets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1"> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_tweets/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>MineTweets</title>
</head>

<body>

  <div class="tweetEntry-tweetHolder">
  
    <p> <%= link_to 'Back to Home', hashtags_path %> </p>

    <% Tweet.all.each do | tw | %>

      <div class="tweetEntry">

        <div class="tweetEntry-content">

          <img class="tweetEntry-avatar" src= <%= tw.url_img_user %> >

          <strong class="tweetEntry-fullname"> <%= tw.user_name %> </strong>

          <span class="tweetEntry-username"> <b> @<%= tw.user_screen_name %> </b> </span>

          <span class="tweetEntry-timestamp"> <%= tw.date_post %> </span>

          <div class="tweetEntry-text-container"> <%= tw.tweet_desc %> </div>

        </div>
      </div>
    <% end %>
  </div>

</body>

</html>